apiVersion: v1
data:
  dbname: evergreen_speakbuddybe_db
  dbuser: root
  serverport: "8081"
  dbhost: mysql.db-ns.svc.cluster.local:3306
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: speakbuddybe-cm
  namespace: speakbuddybe-ns
