apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: speakbuddybeapi
  name: speakbuddybeapi
  namespace: speakbuddybe-ns
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: speakbuddybeapi
status:
  loadBalancer: {}
